--Netflix project
DROP TABLE IF EXISTS public.netflix;
CREATE TABLE public.netflix(
show_id	VARCHAR(6),
net_type VARCHAR(30),
title VARCHAR(150),
director VARCHAR(208),
casts VARCHAR(1000),
country VARCHAR(150),
date_added VARCHAR(50),
release_year INT,
rating VARCHAR(10),
duration VARCHAR(15),
listed_in VARCHAR(150),
description VARCHAR(250));


SELECT * FROM NETFLIX;

SELECT COUNT(*) AS TOTAL_CONTENT FROM NETFLIX;

SELECT DISTINCT(net_type) FROM netflix;

--problems
--Q.1 COUNT THE NO. OF MOVIES VS TV SHOWS
SELECT 
net_type,
COUNT(net_type)
AS NET_TYPE_COUNT
FROM netflix
GROUP BY net_type;

--Q.2 FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS
SELECT 
net_type,
MAX(rating)
AS MOST_COMMON_FOR_NET_TYPE
FROM netflix
GROUP BY net_type;

--Q.3 LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR
SELECT * FROM netflix
WHERE  net_type='Movie'
AND
release_year=2020;

--Q.4 FIND THE TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFLIX
SELECT * FROM netflix;
SELECT 
UNNEST(STRING_TO_ARRAY(country,',')) AS NEW_COUNTRY,
COUNT(show_id) AS NEW_COUNT
FROM netflix
GROUP BY NEW_COUNTRY
ORDER BY NEW_COUNT
DESC
LIMIT 5;

SELECT 
UNNEST(STRING_TO_ARRAY(country,',')) AS NEW_COUNTRY FROM netflix;

--Q.5 IDENTIFY THE LONGEST MOVIE
SELECT * FROM netflix
WHERE net_type='Movie'
AND
duration=(SELECT MAX(duration) FROM netflix WHERE net_type='Movie');

--Q.6 FIND THE CONTENT THAT ADDED IN LAST 5 YEARS
SELECT *
FROM netflix
WHERE TO_DATE(date_added,'Month DD,YYYY') >= CURRENT_DATE - INTERVAL '5 years';

--Q.7 FIND ALL MOVIES/TV SHOWS BY DIRECTOR 'RAJIV CHILAKA'!
SELECT *,
UNNEST(STRING_TO_ARRAY(director,','))AS DIRECTOR
FROM netflix
WHERE director='Rajiv Chilaka';

SELECT *
FROM netflix
WHERE
director ILIKE '%Rajiv Chilaka%';

--Q.8 LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS
SELECT * FROM netflix;

SELECT * FROM netflix
WHERE 
net_type='TV Show' 
AND
SPLIT_PART(duration,' ',1)::numeric > 5;

--Q.9 COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE
SELECT
UNNEST(STRING_TO_ARRAY(listed_in, ',')) AS GENRE,
COUNT(show_id) AS content_count
FROM netflix
GROUP BY GENRE;

/*Q.10 FIND EACH YEAR AND THE AVERAGE NUMBERS OF CONTENT RELEASED IN INDIA ON NETFLIX.
RETURN TOP 5 YEAR WITH HIGHEST AVG CONTENT RELEASE !*/
SELECT 
EXTRACT(YEAR FROM TO_DATE(date_added,'Month DD, YYYY')) AS YEAR,
COUNT(*)
FROM NETFLIX
WHERE country='India'
GROUP BY YEAR;

--Q.11 LIST ALL MOVIES THAT ARE DOCUMENTARIES
SELECT * FROM netflix;

SELECT net_type,title,listed_in
FROM netflix
WHERE
net_type='Movie'
AND
listed_in ILIKE'%Documentaries%';

--Q.12 FIND ALL CONTENT WITHOUT A DIRECTOR
SELECT * FROM netflix;

SELECT * FROM netflix
WHERE
director IS NULL;

--Q.13 FIND HOW MANY MOVIES ACTOR 'Salman Khan' APPEARED IN LAST 10 YEARS:
SELECT *
FROM netflix
WHERE casts ILIKE '%Salman Khan%'
AND 
release_year > EXTRACT(YEAR FROM CURRENT_DATE) - 10 ;

--Q.14 FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN INDIA.
SELECT
UNNEST(STRING_TO_ARRAY(casts,',')) AS ACTOR,
COUNT(CASE WHEN net_type='Movie' THEN 1 END) AS TOTAL_COUNT
FROM netflix
WHERE country ILIKE '%India%'
GROUP BY ACTOR
ORDER BY TOTAL_COUNT
DESC LIMIT 10;

/*Q.15 CATEGORIZE THE CONTENT BASED ON THE PRESENCE OF KEYWORDS 'KILL' AND 'VIOLENCE' IN
THE DESCRIPTION FIELD.LABEL CONTENT CONTAINING THESE KEYWORDS AS 'BAD' AND ALL OTHER
CONTENT AS 'GOOD'.COUNT HOW MANY ITEMS FALL INTO EACH CATEGORY. */

WITH NEW_TABLE
AS
(
SELECT *,
  CASE
  WHEN
     description ILIKE '%kill%'
     OR
     description ILIKE '%violence%'
     THEN 'BAD CONTENT'
     ELSE 'GOOD CONTENT'
  END CATEGORY
FROM netflix
)
SELECT
      category,
	  COUNT(category) AS TOTAL_COUNT
	  FROM NEW_TABLE
	  GROUP BY 1;